public class ExceptionHelper {
    
    public virtual class IntegracaoException extends Exception {
        
    }
	
    public virtual class IntegracaoSiengeException extends Exception {
        
    }
    
    public virtual class IntegracaoZenviaException extends Exception {
        
    }
    
    public virtual class RoteamentoLeadsException extends Exception {
        
    }
    
    public virtual class OmnichannelException extends Exception {
        
    }
    
    public virtual class UraException extends Exception {
        
    }

    public virtual class AcaoException extends Exception {
        
    }
    
    public virtual class FieldServiceException extends Exception {
        
    }
    public virtual class CaseException extends Exception {}
    
    public virtual class GlobalException extends Exception {}
    
}